---
name: e2e-test
on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_call:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  e2e-test-amd64:
    name: Docker - Test amd64
    uses: ./.github/workflows/e2e-checks.yaml
    with:
      platform: amd64

  e2e-test-arm64:
    name: Docker - Test arm64
    uses: ./.github/workflows/e2e-checks.yaml
    with:
      platform: arm64
